---
- name: apply common configuration
  hosts: all
  roles:
  - common

- name: set up openshift build hosts
  hosts: osv3_masters
  roles:
  # install openshift (configure the method in group_vars/all)
  - install-openshift

  # set up OSBS builder
  - osbs-master

  # pull or build the atomic-reactor build image
  - atomic-reactor

  # If you want to import pulp certificate and key into openshift to be later
  # used by atomic-reactor, uncomment the following line and change
  # pulp_secret_local_dir to a directory that contains pulp.cer an pulp.key
  # files. If you already have the secrets on the remote machine use the second
  # form below.
  #- { role: pulp-secret, pulp_secret_local_dir: /home/username/.pulp }
  #- { role: pulp-secret, pulp_secret_remote_dir: /mnt/sync/pulp_secrets }

- name: set up authenticating proxy
  hosts: auth_proxies
  roles:
  - role: osbs-proxy
    # Uncomment the following lines for simple proxy suitable for development.
    #osbs_proxy_ssl_generate_selfsigned: true
    #osbs_proxy_htpasswd_users:
    #- user: test
    #  password: test
