---
- name: apply common configuration
  hosts: all
  roles:
  - common

- name: set up openshift build hosts
  hosts: osv3_masters
  roles:
  # uncomment one of these install methods:
  # (this will eventually be replaced by some openshift role(s) from
  # openshift-ansible)
  - install_openshift_copr
  # useful mostly for ARM builds or building unreleased git versions
  #- install_openshift_source

  # change behind_auth_proxy to true when using authenticating proxy
  - { role: osbs_builder, behind_auth_proxy: false }

  # Pull or build atomic-reactor build image
  - atomic_reactor

  # If you want to import pulp certificate and key into openshift to be later
  # used by atomic-reactor, uncomment the following line and change
  # pulp_secret_local_dir to a directory that contains pulp.cer an pulp.key
  # files.
  #- { role: pulp_secret, pulp_secret_local_dir: /home/username/.pulp }

- name: set up authenticating proxy
  hosts: auth_proxies
  roles:
  - auth_proxy
