---
- name: apply common configuration and install openshift
  hosts: all
  roles:
  - common
  # install openshift (configure the method in group_vars/all)
  - install-openshift


- name: set up openshift master
  hosts: osv3_masters
  roles:
  - role: osbs-master
    osbs_nodes: "{{ groups['osv3_nodes'] }}"

  # If you want to import pulp certificate and key into openshift to be later
  # used by atomic-reactor, uncomment the following line and change
  # pulp_secret_local_dir to a directory that contains pulp.cer an pulp.key
  # files. If you already have the secrets on the remote machine use the second
  # form below.
  #- { role: pulp-secret, pulp_secret_local_dir: /home/username/.pulp }
  #- { role: pulp-secret, pulp_secret_remote_dir: /mnt/sync/pulp_secrets }


- name: set up openshift nodes
  hosts: osv3_nodes
  roles:
  - osbs-node
  # pull or build the atomic-reactor build image
  - atomic-reactor


- name: set up authenticating proxy
  hosts: auth_proxies
  roles:
  - role: osbs-proxy
    # Uncomment the following lines for simple proxy suitable for development.
    #osbs_proxy_ssl_generate_selfsigned: true
    #osbs_proxy_htpasswd_users:
    #- user: test
    #  password: test
