---
# set hostname of each machine to the corresponding fqdn in inventory (hosts)
# file
set_hostname: false

# set to false if you don't use firewalld or do not want the playbook to modify it
manage_firewall: true
