---
- name: ensure kerberos-related packages are installed
  yum: name={{ item }} state=present
  with_items:
  - krb5-workstation
  - mod_auth_kerb

# Based on https://github.com/bennojoy/kerberos_client
# BSD licensed
- name: configure kerberos client
  template: src=krb5.conf.j2 dest=/etc/krb5.conf

- name: set permissions on kerberos keytab
  file:
    path: "{{ proxy_kerberos_keytab_file }}"
    state: file
    owner: "{{ proxy_secrets_owner }}"
    group: "{{ proxy_secrets_group }}"
    mode: "{{ proxy_secrets_perms }}"
