---
## docker needs to know which registries are insecure
insecure_registries: []

# is authenticating proxy in front of us? if true, do not expose openshift port
# and require users to be authenticated
# set to false for debugging
behind_auth_proxy: true

# set to false if you don't use firewalld or do not want the playbook to modify it
manage_firewall: true
