---
- name: copy repository file
  template: src=mmilata-openshift.repo.j2 dest=/etc/yum.repos.d/mmilata-openshift.repo

- name: install openshift
  yum: name=openshift-{{ openshift_version }}*osbs* state=installed
