---
- name: install basic packages
  yum: name={{ item }} state=installed
  with_items:
  - vim
  - tmux
  - wget
  - git
  - net-tools
  - yum-utils

- name: enable rhel7 repos
  command: yum-config-manager --enable {{ item }}
  with_items:
  - rhel-7-server-optional-rpms
  - rhel-7-server-extras-rpms
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: enable epel7
  yum: name={{ epel7_url }} state=installed
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
